/**
 * This file has been automatically generated by the [capnpc-ts utility](https://github.com/jdiaz5513/capnp-ts).
 */
import * as capnp from "capnp-ts";
import { Struct as __S } from 'capnp-ts';
export declare const _capnpFileId = "a1b2c3d4e5f60002";
export declare class TurnBasedReplay extends __S {
    static readonly _capnp: {
        displayName: string;
        id: string;
        size: capnp.ObjectSize;
    };
    static _Moves: capnp.ListCtor<SignedMove>;
    adoptInitialState(value: capnp.Orphan<capnp.Data>): void;
    disownInitialState(): capnp.Orphan<capnp.Data>;
    getInitialState(): capnp.Data;
    hasInitialState(): boolean;
    initInitialState(length: number): capnp.Data;
    setInitialState(value: capnp.Data): void;
    adoptMoves(value: capnp.Orphan<capnp.List<SignedMove>>): void;
    disownMoves(): capnp.Orphan<capnp.List<SignedMove>>;
    getMoves(): capnp.List<SignedMove>;
    hasMoves(): boolean;
    initMoves(length: number): capnp.List<SignedMove>;
    setMoves(value: capnp.List<SignedMove>): void;
    toString(): string;
}
export declare class SignedMove extends __S {
    static readonly _capnp: {
        displayName: string;
        id: string;
        size: capnp.ObjectSize;
    };
    getPlayerId(): number;
    setPlayerId(value: number): void;
    adoptMoveData(value: capnp.Orphan<capnp.Data>): void;
    disownMoveData(): capnp.Orphan<capnp.Data>;
    getMoveData(): capnp.Data;
    hasMoveData(): boolean;
    initMoveData(length: number): capnp.Data;
    setMoveData(value: capnp.Data): void;
    getTimestamp(): capnp.Uint64;
    setTimestamp(value: capnp.Uint64): void;
    adoptSignature(value: capnp.Orphan<capnp.Data>): void;
    disownSignature(): capnp.Orphan<capnp.Data>;
    getSignature(): capnp.Data;
    hasSignature(): boolean;
    initSignature(length: number): capnp.Data;
    setSignature(value: capnp.Data): void;
    toString(): string;
}
export declare class RealtimeTranscript extends __S {
    static readonly _capnp: {
        displayName: string;
        id: string;
        size: capnp.ObjectSize;
    };
    static _Snapshots: capnp.ListCtor<StateSnapshot>;
    adoptSnapshots(value: capnp.Orphan<capnp.List<StateSnapshot>>): void;
    disownSnapshots(): capnp.Orphan<capnp.List<StateSnapshot>>;
    getSnapshots(): capnp.List<StateSnapshot>;
    hasSnapshots(): boolean;
    initSnapshots(length: number): capnp.List<StateSnapshot>;
    setSnapshots(value: capnp.List<StateSnapshot>): void;
    adoptInputs(value: capnp.Orphan<capnp.Data>): void;
    disownInputs(): capnp.Orphan<capnp.Data>;
    getInputs(): capnp.Data;
    hasInputs(): boolean;
    initInputs(length: number): capnp.Data;
    setInputs(value: capnp.Data): void;
    toString(): string;
}
export declare class StateSnapshot extends __S {
    static readonly _capnp: {
        displayName: string;
        id: string;
        size: capnp.ObjectSize;
    };
    getFrameId(): capnp.Uint64;
    setFrameId(value: capnp.Uint64): void;
    adoptStateHash(value: capnp.Orphan<capnp.Data>): void;
    disownStateHash(): capnp.Orphan<capnp.Data>;
    getStateHash(): capnp.Data;
    hasStateHash(): boolean;
    initStateHash(length: number): capnp.Data;
    setStateHash(value: capnp.Data): void;
    adoptSignatures(value: capnp.Orphan<capnp.List<capnp.Data>>): void;
    disownSignatures(): capnp.Orphan<capnp.List<capnp.Data>>;
    getSignatures(): capnp.List<capnp.Data>;
    hasSignatures(): boolean;
    initSignatures(length: number): capnp.List<capnp.Data>;
    setSignatures(value: capnp.List<capnp.Data>): void;
    toString(): string;
}
export declare class OracleResult extends __S {
    static readonly _capnp: {
        displayName: string;
        id: string;
        size: capnp.ObjectSize;
    };
    getSource(): string;
    setSource(value: string): void;
    adoptQueryId(value: capnp.Orphan<capnp.Data>): void;
    disownQueryId(): capnp.Orphan<capnp.Data>;
    getQueryId(): capnp.Data;
    hasQueryId(): boolean;
    initQueryId(length: number): capnp.Data;
    setQueryId(value: capnp.Data): void;
    adoptResult(value: capnp.Orphan<capnp.Data>): void;
    disownResult(): capnp.Orphan<capnp.Data>;
    getResult(): capnp.Data;
    hasResult(): boolean;
    initResult(length: number): capnp.Data;
    setResult(value: capnp.Data): void;
    adoptProof(value: capnp.Orphan<capnp.Data>): void;
    disownProof(): capnp.Orphan<capnp.Data>;
    getProof(): capnp.Data;
    hasProof(): boolean;
    initProof(length: number): capnp.Data;
    setProof(value: capnp.Data): void;
    toString(): string;
}
