"use strict";
/* tslint:disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.OracleResult = exports.StateSnapshot = exports.RealtimeTranscript = exports.SignedMove = exports.TurnBasedReplay = exports._capnpFileId = void 0;
/**
 * This file has been automatically generated by the [capnpc-ts utility](https://github.com/jdiaz5513/capnp-ts).
 */
const capnp = require("capnp-ts");
const capnp_ts_1 = require("capnp-ts");
exports._capnpFileId = "a1b2c3d4e5f60002";
class TurnBasedReplay extends capnp_ts_1.Struct {
    adoptInitialState(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownInitialState() { return capnp_ts_1.Struct.disown(this.getInitialState()); }
    getInitialState() { return capnp_ts_1.Struct.getData(0, this); }
    hasInitialState() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initInitialState(length) { return capnp_ts_1.Struct.initData(0, length, this); }
    setInitialState(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    adoptMoves(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownMoves() { return capnp_ts_1.Struct.disown(this.getMoves()); }
    getMoves() { return capnp_ts_1.Struct.getList(1, TurnBasedReplay._Moves, this); }
    hasMoves() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initMoves(length) { return capnp_ts_1.Struct.initList(1, TurnBasedReplay._Moves, length, this); }
    setMoves(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    toString() { return "TurnBasedReplay_" + super.toString(); }
}
exports.TurnBasedReplay = TurnBasedReplay;
TurnBasedReplay._capnp = { displayName: "TurnBasedReplay", id: "c112e9e4e9063aa7", size: new capnp_ts_1.ObjectSize(0, 2) };
class SignedMove extends capnp_ts_1.Struct {
    getPlayerId() { return capnp_ts_1.Struct.getUint8(0, this); }
    setPlayerId(value) { capnp_ts_1.Struct.setUint8(0, value, this); }
    adoptMoveData(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownMoveData() { return capnp_ts_1.Struct.disown(this.getMoveData()); }
    getMoveData() { return capnp_ts_1.Struct.getData(0, this); }
    hasMoveData() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initMoveData(length) { return capnp_ts_1.Struct.initData(0, length, this); }
    setMoveData(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    getTimestamp() { return capnp_ts_1.Struct.getUint64(8, this); }
    setTimestamp(value) { capnp_ts_1.Struct.setUint64(8, value, this); }
    adoptSignature(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownSignature() { return capnp_ts_1.Struct.disown(this.getSignature()); }
    getSignature() { return capnp_ts_1.Struct.getData(1, this); }
    hasSignature() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initSignature(length) { return capnp_ts_1.Struct.initData(1, length, this); }
    setSignature(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    toString() { return "SignedMove_" + super.toString(); }
}
exports.SignedMove = SignedMove;
SignedMove._capnp = { displayName: "SignedMove", id: "8c1009f863514607", size: new capnp_ts_1.ObjectSize(16, 2) };
class RealtimeTranscript extends capnp_ts_1.Struct {
    adoptSnapshots(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownSnapshots() { return capnp_ts_1.Struct.disown(this.getSnapshots()); }
    getSnapshots() { return capnp_ts_1.Struct.getList(0, RealtimeTranscript._Snapshots, this); }
    hasSnapshots() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initSnapshots(length) { return capnp_ts_1.Struct.initList(0, RealtimeTranscript._Snapshots, length, this); }
    setSnapshots(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    adoptInputs(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownInputs() { return capnp_ts_1.Struct.disown(this.getInputs()); }
    getInputs() { return capnp_ts_1.Struct.getData(1, this); }
    hasInputs() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initInputs(length) { return capnp_ts_1.Struct.initData(1, length, this); }
    setInputs(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    toString() { return "RealtimeTranscript_" + super.toString(); }
}
exports.RealtimeTranscript = RealtimeTranscript;
RealtimeTranscript._capnp = { displayName: "RealtimeTranscript", id: "ecb22473c992d36e", size: new capnp_ts_1.ObjectSize(0, 2) };
class StateSnapshot extends capnp_ts_1.Struct {
    getFrameId() { return capnp_ts_1.Struct.getUint64(0, this); }
    setFrameId(value) { capnp_ts_1.Struct.setUint64(0, value, this); }
    adoptStateHash(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownStateHash() { return capnp_ts_1.Struct.disown(this.getStateHash()); }
    getStateHash() { return capnp_ts_1.Struct.getData(0, this); }
    hasStateHash() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initStateHash(length) { return capnp_ts_1.Struct.initData(0, length, this); }
    setStateHash(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    adoptSignatures(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownSignatures() { return capnp_ts_1.Struct.disown(this.getSignatures()); }
    getSignatures() { return capnp_ts_1.Struct.getList(1, capnp.DataList, this); }
    hasSignatures() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initSignatures(length) { return capnp_ts_1.Struct.initList(1, capnp.DataList, length, this); }
    setSignatures(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    toString() { return "StateSnapshot_" + super.toString(); }
}
exports.StateSnapshot = StateSnapshot;
StateSnapshot._capnp = { displayName: "StateSnapshot", id: "928b3870870d29bf", size: new capnp_ts_1.ObjectSize(8, 2) };
class OracleResult extends capnp_ts_1.Struct {
    getSource() { return capnp_ts_1.Struct.getText(0, this); }
    setSource(value) { capnp_ts_1.Struct.setText(0, value, this); }
    adoptQueryId(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownQueryId() { return capnp_ts_1.Struct.disown(this.getQueryId()); }
    getQueryId() { return capnp_ts_1.Struct.getData(1, this); }
    hasQueryId() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initQueryId(length) { return capnp_ts_1.Struct.initData(1, length, this); }
    setQueryId(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    adoptResult(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(2, this)); }
    disownResult() { return capnp_ts_1.Struct.disown(this.getResult()); }
    getResult() { return capnp_ts_1.Struct.getData(2, this); }
    hasResult() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(2, this)); }
    initResult(length) { return capnp_ts_1.Struct.initData(2, length, this); }
    setResult(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(2, this)); }
    adoptProof(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(3, this)); }
    disownProof() { return capnp_ts_1.Struct.disown(this.getProof()); }
    getProof() { return capnp_ts_1.Struct.getData(3, this); }
    hasProof() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(3, this)); }
    initProof(length) { return capnp_ts_1.Struct.initData(3, length, this); }
    setProof(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(3, this)); }
    toString() { return "OracleResult_" + super.toString(); }
}
exports.OracleResult = OracleResult;
OracleResult._capnp = { displayName: "OracleResult", id: "b775b35e74a8319b", size: new capnp_ts_1.ObjectSize(0, 4) };
TurnBasedReplay._Moves = capnp.CompositeList(SignedMove);
RealtimeTranscript._Snapshots = capnp.CompositeList(StateSnapshot);
