/**
 * This file has been automatically generated by the [capnpc-ts utility](https://github.com/jdiaz5513/capnp-ts).
 */
import * as capnp from "capnp-ts";
import { Struct as __S } from 'capnp-ts';
export declare const _capnpFileId = "a1b2c3d4e5f60001";
export declare enum MatchType {
    TURN_BASED = 0,
    REAL_TIME = 1
}
export declare enum Region {
    NA = 0,
    EU = 1,
    SA = 2,
    AS = 3
}
export declare enum Elo {
    UNRANKED = 0,
    BRONZE = 1,
    SILVER = 2,
    GOLD = 3,
    PLATINUM = 4,
    DIAMOND = 5,
    MASTER = 6,
    GRANDMASTER = 7
}
export declare class PaymentInfo extends __S {
    static readonly _capnp: {
        displayName: string;
        id: string;
        size: capnp.ObjectSize;
    };
    adoptPayerWallet(value: capnp.Orphan<capnp.Data>): void;
    disownPayerWallet(): capnp.Orphan<capnp.Data>;
    getPayerWallet(): capnp.Data;
    hasPayerWallet(): boolean;
    initPayerWallet(length: number): capnp.Data;
    setPayerWallet(value: capnp.Data): void;
    adoptFeeToken(value: capnp.Orphan<capnp.Data>): void;
    disownFeeToken(): capnp.Orphan<capnp.Data>;
    getFeeToken(): capnp.Data;
    hasFeeToken(): boolean;
    initFeeToken(length: number): capnp.Data;
    setFeeToken(value: capnp.Data): void;
    getAuthSpend(): capnp.Uint64;
    setAuthSpend(value: capnp.Uint64): void;
    toString(): string;
}
export declare class PlayerInfo extends __S {
    static readonly _capnp: {
        displayName: string;
        id: string;
        size: capnp.ObjectSize;
    };
    adoptPlayerId(value: capnp.Orphan<capnp.Data>): void;
    disownPlayerId(): capnp.Orphan<capnp.Data>;
    getPlayerId(): capnp.Data;
    hasPlayerId(): boolean;
    initPlayerId(length: number): capnp.Data;
    setPlayerId(value: capnp.Data): void;
    getDisplayName(): string;
    setDisplayName(value: string): void;
    adoptPlayerWallet(value: capnp.Orphan<capnp.Data>): void;
    disownPlayerWallet(): capnp.Orphan<capnp.Data>;
    getPlayerWallet(): capnp.Data;
    hasPlayerWallet(): boolean;
    initPlayerWallet(length: number): capnp.Data;
    setPlayerWallet(value: capnp.Data): void;
    getElo(): Elo;
    setElo(value: Elo): void;
    getRegion(): Region;
    setRegion(value: Region): void;
    toString(): string;
}
export declare class GameMatchRequest extends __S {
    static readonly _capnp: {
        displayName: string;
        id: string;
        size: capnp.ObjectSize;
    };
    adoptGameId(value: capnp.Orphan<capnp.Data>): void;
    disownGameId(): capnp.Orphan<capnp.Data>;
    getGameId(): capnp.Data;
    hasGameId(): boolean;
    initGameId(length: number): capnp.Data;
    setGameId(value: capnp.Data): void;
    getRulesType(): string;
    setRulesType(value: string): void;
    adoptStake(value: capnp.Orphan<PaymentInfo>): void;
    disownStake(): capnp.Orphan<PaymentInfo>;
    getStake(): PaymentInfo;
    hasStake(): boolean;
    initStake(): PaymentInfo;
    setStake(value: PaymentInfo): void;
    adoptPlayerInfo(value: capnp.Orphan<PlayerInfo>): void;
    disownPlayerInfo(): capnp.Orphan<PlayerInfo>;
    getPlayerInfo(): PlayerInfo;
    hasPlayerInfo(): boolean;
    initPlayerInfo(): PlayerInfo;
    setPlayerInfo(value: PlayerInfo): void;
    adoptOptionalConfig(value: capnp.Orphan<capnp.Data>): void;
    disownOptionalConfig(): capnp.Orphan<capnp.Data>;
    getOptionalConfig(): capnp.Data;
    hasOptionalConfig(): boolean;
    initOptionalConfig(length: number): capnp.Data;
    setOptionalConfig(value: capnp.Data): void;
    toString(): string;
}
export declare class MatchAssignment extends __S {
    static readonly _capnp: {
        displayName: string;
        id: string;
        size: capnp.ObjectSize;
    };
    static _Opponents: capnp.ListCtor<PlayerInfo>;
    adoptMatchId(value: capnp.Orphan<capnp.Data>): void;
    disownMatchId(): capnp.Orphan<capnp.Data>;
    getMatchId(): capnp.Data;
    hasMatchId(): boolean;
    initMatchId(length: number): capnp.Data;
    setMatchId(value: capnp.Data): void;
    adoptOpponents(value: capnp.Orphan<capnp.List<PlayerInfo>>): void;
    disownOpponents(): capnp.Orphan<capnp.List<PlayerInfo>>;
    getOpponents(): capnp.List<PlayerInfo>;
    hasOpponents(): boolean;
    initOpponents(length: number): capnp.List<PlayerInfo>;
    setOpponents(value: capnp.List<PlayerInfo>): void;
    adoptGameConfig(value: capnp.Orphan<capnp.Data>): void;
    disownGameConfig(): capnp.Orphan<capnp.Data>;
    getGameConfig(): capnp.Data;
    hasGameConfig(): boolean;
    initGameConfig(length: number): capnp.Data;
    setGameConfig(value: capnp.Data): void;
    adoptAssignedVerifier(value: capnp.Orphan<capnp.Data>): void;
    disownAssignedVerifier(): capnp.Orphan<capnp.Data>;
    getAssignedVerifier(): capnp.Data;
    hasAssignedVerifier(): boolean;
    initAssignedVerifier(length: number): capnp.Data;
    setAssignedVerifier(value: capnp.Data): void;
    toString(): string;
}
export declare enum OutcomeType {
    UNKNOWN = 0,
    WIN = 1,
    DRAW = 2,
    VOID = 3
}
export declare class Outcome extends __S {
    static readonly _capnp: {
        displayName: string;
        id: string;
        size: capnp.ObjectSize;
    };
    getType(): OutcomeType;
    setType(value: OutcomeType): void;
    adoptScores(value: capnp.Orphan<capnp.List<capnp.Uint64>>): void;
    disownScores(): capnp.Orphan<capnp.List<capnp.Uint64>>;
    getScores(): capnp.List<capnp.Uint64>;
    hasScores(): boolean;
    initScores(length: number): capnp.List<capnp.Uint64>;
    setScores(value: capnp.List<capnp.Uint64>): void;
    getVictor(): number;
    setVictor(value: number): void;
    adoptMetadata(value: capnp.Orphan<capnp.Data>): void;
    disownMetadata(): capnp.Orphan<capnp.Data>;
    getMetadata(): capnp.Data;
    hasMetadata(): boolean;
    initMetadata(length: number): capnp.Data;
    setMetadata(value: capnp.Data): void;
    toString(): string;
}
export declare class OutcomeSubmission extends __S {
    static readonly _capnp: {
        displayName: string;
        id: string;
        size: capnp.ObjectSize;
    };
    adoptMatchId(value: capnp.Orphan<capnp.Data>): void;
    disownMatchId(): capnp.Orphan<capnp.Data>;
    getMatchId(): capnp.Data;
    hasMatchId(): boolean;
    initMatchId(length: number): capnp.Data;
    setMatchId(value: capnp.Data): void;
    adoptOutcome(value: capnp.Orphan<Outcome>): void;
    disownOutcome(): capnp.Orphan<Outcome>;
    getOutcome(): Outcome;
    hasOutcome(): boolean;
    initOutcome(): Outcome;
    setOutcome(value: Outcome): void;
    adoptReplayHash(value: capnp.Orphan<capnp.Data>): void;
    disownReplayHash(): capnp.Orphan<capnp.Data>;
    getReplayHash(): capnp.Data;
    hasReplayHash(): boolean;
    initReplayHash(length: number): capnp.Data;
    setReplayHash(value: capnp.Data): void;
    adoptSignature(value: capnp.Orphan<capnp.Data>): void;
    disownSignature(): capnp.Orphan<capnp.Data>;
    getSignature(): capnp.Data;
    hasSignature(): boolean;
    initSignature(length: number): capnp.Data;
    setSignature(value: capnp.Data): void;
    toString(): string;
}
export declare class MatchTranscript extends __S {
    static readonly _capnp: {
        displayName: string;
        id: string;
        size: capnp.ObjectSize;
    };
    adoptMatchId(value: capnp.Orphan<capnp.Data>): void;
    disownMatchId(): capnp.Orphan<capnp.Data>;
    getMatchId(): capnp.Data;
    hasMatchId(): boolean;
    initMatchId(length: number): capnp.Data;
    setMatchId(value: capnp.Data): void;
    adoptEvents(value: capnp.Orphan<capnp.List<capnp.Data>>): void;
    disownEvents(): capnp.Orphan<capnp.List<capnp.Data>>;
    getEvents(): capnp.List<capnp.Data>;
    hasEvents(): boolean;
    initEvents(length: number): capnp.List<capnp.Data>;
    setEvents(value: capnp.List<capnp.Data>): void;
    adoptFinalStateHash(value: capnp.Orphan<capnp.Data>): void;
    disownFinalStateHash(): capnp.Orphan<capnp.Data>;
    getFinalStateHash(): capnp.Data;
    hasFinalStateHash(): boolean;
    initFinalStateHash(length: number): capnp.Data;
    setFinalStateHash(value: capnp.Data): void;
    toString(): string;
}
