"use strict";
/* tslint:disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.MatchTranscript = exports.OutcomeSubmission = exports.Outcome = exports.OutcomeType = exports.MatchAssignment = exports.GameMatchRequest = exports.PlayerInfo = exports.PaymentInfo = exports.Elo = exports.Region = exports.MatchType = exports._capnpFileId = void 0;
/**
 * This file has been automatically generated by the [capnpc-ts utility](https://github.com/jdiaz5513/capnp-ts).
 */
const capnp = require("capnp-ts");
const capnp_ts_1 = require("capnp-ts");
exports._capnpFileId = "a1b2c3d4e5f60001";
var MatchType;
(function (MatchType) {
    MatchType[MatchType["TURN_BASED"] = 0] = "TURN_BASED";
    MatchType[MatchType["REAL_TIME"] = 1] = "REAL_TIME";
})(MatchType = exports.MatchType || (exports.MatchType = {}));
var Region;
(function (Region) {
    Region[Region["NA"] = 0] = "NA";
    Region[Region["EU"] = 1] = "EU";
    Region[Region["SA"] = 2] = "SA";
    Region[Region["AS"] = 3] = "AS";
})(Region = exports.Region || (exports.Region = {}));
var Elo;
(function (Elo) {
    Elo[Elo["UNRANKED"] = 0] = "UNRANKED";
    Elo[Elo["BRONZE"] = 1] = "BRONZE";
    Elo[Elo["SILVER"] = 2] = "SILVER";
    Elo[Elo["GOLD"] = 3] = "GOLD";
    Elo[Elo["PLATINUM"] = 4] = "PLATINUM";
    Elo[Elo["DIAMOND"] = 5] = "DIAMOND";
    Elo[Elo["MASTER"] = 6] = "MASTER";
    Elo[Elo["GRANDMASTER"] = 7] = "GRANDMASTER";
})(Elo = exports.Elo || (exports.Elo = {}));
class PaymentInfo extends capnp_ts_1.Struct {
    adoptPayerWallet(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownPayerWallet() { return capnp_ts_1.Struct.disown(this.getPayerWallet()); }
    getPayerWallet() { return capnp_ts_1.Struct.getData(0, this); }
    hasPayerWallet() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initPayerWallet(length) { return capnp_ts_1.Struct.initData(0, length, this); }
    setPayerWallet(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    adoptFeeToken(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownFeeToken() { return capnp_ts_1.Struct.disown(this.getFeeToken()); }
    getFeeToken() { return capnp_ts_1.Struct.getData(1, this); }
    hasFeeToken() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initFeeToken(length) { return capnp_ts_1.Struct.initData(1, length, this); }
    setFeeToken(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    getAuthSpend() { return capnp_ts_1.Struct.getUint64(0, this); }
    setAuthSpend(value) { capnp_ts_1.Struct.setUint64(0, value, this); }
    toString() { return "PaymentInfo_" + super.toString(); }
}
exports.PaymentInfo = PaymentInfo;
PaymentInfo._capnp = { displayName: "PaymentInfo", id: "b6df84125444afe7", size: new capnp_ts_1.ObjectSize(8, 2) };
class PlayerInfo extends capnp_ts_1.Struct {
    adoptPlayerId(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownPlayerId() { return capnp_ts_1.Struct.disown(this.getPlayerId()); }
    getPlayerId() { return capnp_ts_1.Struct.getData(0, this); }
    hasPlayerId() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initPlayerId(length) { return capnp_ts_1.Struct.initData(0, length, this); }
    setPlayerId(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    getDisplayName() { return capnp_ts_1.Struct.getText(1, this); }
    setDisplayName(value) { capnp_ts_1.Struct.setText(1, value, this); }
    adoptPlayerWallet(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(2, this)); }
    disownPlayerWallet() { return capnp_ts_1.Struct.disown(this.getPlayerWallet()); }
    getPlayerWallet() { return capnp_ts_1.Struct.getData(2, this); }
    hasPlayerWallet() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(2, this)); }
    initPlayerWallet(length) { return capnp_ts_1.Struct.initData(2, length, this); }
    setPlayerWallet(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(2, this)); }
    getElo() { return capnp_ts_1.Struct.getUint16(0, this); }
    setElo(value) { capnp_ts_1.Struct.setUint16(0, value, this); }
    getRegion() { return capnp_ts_1.Struct.getUint16(2, this); }
    setRegion(value) { capnp_ts_1.Struct.setUint16(2, value, this); }
    toString() { return "PlayerInfo_" + super.toString(); }
}
exports.PlayerInfo = PlayerInfo;
PlayerInfo._capnp = { displayName: "PlayerInfo", id: "950900d3a2976912", size: new capnp_ts_1.ObjectSize(8, 3) };
class GameMatchRequest extends capnp_ts_1.Struct {
    adoptGameId(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownGameId() { return capnp_ts_1.Struct.disown(this.getGameId()); }
    getGameId() { return capnp_ts_1.Struct.getData(0, this); }
    hasGameId() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initGameId(length) { return capnp_ts_1.Struct.initData(0, length, this); }
    setGameId(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    getRulesType() { return capnp_ts_1.Struct.getText(1, this); }
    setRulesType(value) { capnp_ts_1.Struct.setText(1, value, this); }
    adoptStake(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(2, this)); }
    disownStake() { return capnp_ts_1.Struct.disown(this.getStake()); }
    getStake() { return capnp_ts_1.Struct.getStruct(2, PaymentInfo, this); }
    hasStake() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(2, this)); }
    initStake() { return capnp_ts_1.Struct.initStructAt(2, PaymentInfo, this); }
    setStake(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(2, this)); }
    adoptPlayerInfo(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(3, this)); }
    disownPlayerInfo() { return capnp_ts_1.Struct.disown(this.getPlayerInfo()); }
    getPlayerInfo() { return capnp_ts_1.Struct.getStruct(3, PlayerInfo, this); }
    hasPlayerInfo() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(3, this)); }
    initPlayerInfo() { return capnp_ts_1.Struct.initStructAt(3, PlayerInfo, this); }
    setPlayerInfo(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(3, this)); }
    adoptOptionalConfig(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(4, this)); }
    disownOptionalConfig() { return capnp_ts_1.Struct.disown(this.getOptionalConfig()); }
    getOptionalConfig() { return capnp_ts_1.Struct.getData(4, this); }
    hasOptionalConfig() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(4, this)); }
    initOptionalConfig(length) { return capnp_ts_1.Struct.initData(4, length, this); }
    setOptionalConfig(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(4, this)); }
    toString() { return "GameMatchRequest_" + super.toString(); }
}
exports.GameMatchRequest = GameMatchRequest;
GameMatchRequest._capnp = { displayName: "GameMatchRequest", id: "bfec7f142f8f0d86", size: new capnp_ts_1.ObjectSize(0, 5) };
class MatchAssignment extends capnp_ts_1.Struct {
    adoptMatchId(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownMatchId() { return capnp_ts_1.Struct.disown(this.getMatchId()); }
    getMatchId() { return capnp_ts_1.Struct.getData(0, this); }
    hasMatchId() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initMatchId(length) { return capnp_ts_1.Struct.initData(0, length, this); }
    setMatchId(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    adoptOpponents(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownOpponents() { return capnp_ts_1.Struct.disown(this.getOpponents()); }
    getOpponents() { return capnp_ts_1.Struct.getList(1, MatchAssignment._Opponents, this); }
    hasOpponents() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initOpponents(length) { return capnp_ts_1.Struct.initList(1, MatchAssignment._Opponents, length, this); }
    setOpponents(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    adoptGameConfig(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(2, this)); }
    disownGameConfig() { return capnp_ts_1.Struct.disown(this.getGameConfig()); }
    getGameConfig() { return capnp_ts_1.Struct.getData(2, this); }
    hasGameConfig() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(2, this)); }
    initGameConfig(length) { return capnp_ts_1.Struct.initData(2, length, this); }
    setGameConfig(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(2, this)); }
    adoptAssignedVerifier(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(3, this)); }
    disownAssignedVerifier() { return capnp_ts_1.Struct.disown(this.getAssignedVerifier()); }
    getAssignedVerifier() { return capnp_ts_1.Struct.getData(3, this); }
    hasAssignedVerifier() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(3, this)); }
    initAssignedVerifier(length) { return capnp_ts_1.Struct.initData(3, length, this); }
    setAssignedVerifier(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(3, this)); }
    toString() { return "MatchAssignment_" + super.toString(); }
}
exports.MatchAssignment = MatchAssignment;
MatchAssignment._capnp = { displayName: "MatchAssignment", id: "a1dc4bc08af66044", size: new capnp_ts_1.ObjectSize(0, 4) };
var OutcomeType;
(function (OutcomeType) {
    OutcomeType[OutcomeType["UNKNOWN"] = 0] = "UNKNOWN";
    OutcomeType[OutcomeType["WIN"] = 1] = "WIN";
    OutcomeType[OutcomeType["DRAW"] = 2] = "DRAW";
    OutcomeType[OutcomeType["VOID"] = 3] = "VOID";
})(OutcomeType = exports.OutcomeType || (exports.OutcomeType = {}));
class Outcome extends capnp_ts_1.Struct {
    getType() { return capnp_ts_1.Struct.getUint16(0, this); }
    setType(value) { capnp_ts_1.Struct.setUint16(0, value, this); }
    adoptScores(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownScores() { return capnp_ts_1.Struct.disown(this.getScores()); }
    getScores() { return capnp_ts_1.Struct.getList(0, capnp.Uint64List, this); }
    hasScores() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initScores(length) { return capnp_ts_1.Struct.initList(0, capnp.Uint64List, length, this); }
    setScores(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    getVictor() { return capnp_ts_1.Struct.getUint8(2, this); }
    setVictor(value) { capnp_ts_1.Struct.setUint8(2, value, this); }
    adoptMetadata(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownMetadata() { return capnp_ts_1.Struct.disown(this.getMetadata()); }
    getMetadata() { return capnp_ts_1.Struct.getData(1, this); }
    hasMetadata() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initMetadata(length) { return capnp_ts_1.Struct.initData(1, length, this); }
    setMetadata(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    toString() { return "Outcome_" + super.toString(); }
}
exports.Outcome = Outcome;
Outcome._capnp = { displayName: "Outcome", id: "a423c8403e5872c3", size: new capnp_ts_1.ObjectSize(8, 2) };
class OutcomeSubmission extends capnp_ts_1.Struct {
    adoptMatchId(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownMatchId() { return capnp_ts_1.Struct.disown(this.getMatchId()); }
    getMatchId() { return capnp_ts_1.Struct.getData(0, this); }
    hasMatchId() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initMatchId(length) { return capnp_ts_1.Struct.initData(0, length, this); }
    setMatchId(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    adoptOutcome(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownOutcome() { return capnp_ts_1.Struct.disown(this.getOutcome()); }
    getOutcome() { return capnp_ts_1.Struct.getStruct(1, Outcome, this); }
    hasOutcome() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initOutcome() { return capnp_ts_1.Struct.initStructAt(1, Outcome, this); }
    setOutcome(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    adoptReplayHash(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(2, this)); }
    disownReplayHash() { return capnp_ts_1.Struct.disown(this.getReplayHash()); }
    getReplayHash() { return capnp_ts_1.Struct.getData(2, this); }
    hasReplayHash() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(2, this)); }
    initReplayHash(length) { return capnp_ts_1.Struct.initData(2, length, this); }
    setReplayHash(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(2, this)); }
    adoptSignature(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(3, this)); }
    disownSignature() { return capnp_ts_1.Struct.disown(this.getSignature()); }
    getSignature() { return capnp_ts_1.Struct.getData(3, this); }
    hasSignature() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(3, this)); }
    initSignature(length) { return capnp_ts_1.Struct.initData(3, length, this); }
    setSignature(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(3, this)); }
    toString() { return "OutcomeSubmission_" + super.toString(); }
}
exports.OutcomeSubmission = OutcomeSubmission;
OutcomeSubmission._capnp = { displayName: "OutcomeSubmission", id: "bc2691552f9e8d28", size: new capnp_ts_1.ObjectSize(0, 4) };
class MatchTranscript extends capnp_ts_1.Struct {
    adoptMatchId(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownMatchId() { return capnp_ts_1.Struct.disown(this.getMatchId()); }
    getMatchId() { return capnp_ts_1.Struct.getData(0, this); }
    hasMatchId() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initMatchId(length) { return capnp_ts_1.Struct.initData(0, length, this); }
    setMatchId(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    adoptEvents(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownEvents() { return capnp_ts_1.Struct.disown(this.getEvents()); }
    getEvents() { return capnp_ts_1.Struct.getList(1, capnp.DataList, this); }
    hasEvents() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initEvents(length) { return capnp_ts_1.Struct.initList(1, capnp.DataList, length, this); }
    setEvents(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    adoptFinalStateHash(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(2, this)); }
    disownFinalStateHash() { return capnp_ts_1.Struct.disown(this.getFinalStateHash()); }
    getFinalStateHash() { return capnp_ts_1.Struct.getData(2, this); }
    hasFinalStateHash() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(2, this)); }
    initFinalStateHash(length) { return capnp_ts_1.Struct.initData(2, length, this); }
    setFinalStateHash(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(2, this)); }
    toString() { return "MatchTranscript_" + super.toString(); }
}
exports.MatchTranscript = MatchTranscript;
MatchTranscript._capnp = { displayName: "MatchTranscript", id: "c889ba49438bfe75", size: new capnp_ts_1.ObjectSize(0, 3) };
MatchAssignment._Opponents = capnp.CompositeList(PlayerInfo);
