version: "3.9"
services:
  amp-telemetry:
    image: rust:latest
    working_dir: /app/amp-telemetry
    volumes:
      - .:/app
    command: >
      sh -c "apt-get update && apt-get install -y libssl-dev && /app/target/release/amp-telemetry"
    environment:
      - CARGO_TARGET_DIR=/tmp/target
    ports:
      - "4317:4317"

  amp-relayer:
    image: rust:latest
    working_dir: /app/amp-relayer
    volumes:
      - .:/app
    command: >
      sh -c "apt-get update && apt-get install -y libssl-dev netcat-openbsd && 
             /app/target/release/amp-relayer"
    environment:
      - FUJI_RPC_URL=${FUJI_RPC_URL}
      - RELAYER_PRIVATE_KEY=${RELAYER_PRIVATE_KEY}
      - CONTRACT_REGISTRY=${CONTRACT_REGISTRY}
      - CONTRACT_SETTLEMENT=${CONTRACT_SETTLEMENT}
      - RPC_PORT=${RPC_PORT}
      - CARGO_TARGET_DIR=/tmp/target
    ports:
      - "${RPC_PORT}:${RPC_PORT}"
    depends_on:
      - amp-telemetry

  amp-server:
    image: rust:latest
    working_dir: /app/amp-server
    volumes:
      - .:/app
    command: >
      sh -c "apt-get update && apt-get install -y libssl-dev netcat-openbsd && 
             echo 'Waiting for Relayer...' &&
             until nc -z amp-relayer 50052; do sleep 2; done &&
             /app/target/release/AMP-Server"
    environment:
      - AMP_ADDR=0.0.0.0:50051
      - VERIFIER_KEY=${VERIFIER_KEY}
      - RELAYER_RPC_ADDR=${RELAYER_RPC_ADDR}
      - TELEMETRY_ADDR=${TELEMETRY_ADDR}
      - CARGO_TARGET_DIR=/tmp/target
    ports:
      - "50051:50051"
    depends_on:
      - amp-telemetry
      - amp-relayer
