// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: rust.capnp

#pragma once

#include <capnp/generated-header-support.h>
#include <kj/windows-sanity.h>

#ifndef CAPNP_VERSION
#error "CAPNP_VERSION is not defined, is capnp/generated-header-support.h missing?"
#elif CAPNP_VERSION != 1002000
#error "Version mismatch between generated code and library headers.  You must use the same version of the Cap'n Proto compiler and library."
#endif


CAPNP_BEGIN_HEADER

namespace capnp {
namespace schemas {

CAPNP_DECLARE_SCHEMA(a1b2c3d4e5f60004);

}  // namespace schemas
}  // namespace capnp


// =======================================================================================

// =======================================================================================


CAPNP_END_HEADER

