// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: service.capnp

#pragma once

#include <capnp/generated-header-support.h>
#include <kj/windows-sanity.h>
#if !CAPNP_LITE
#include <capnp/capability.h>
#endif  // !CAPNP_LITE

#ifndef CAPNP_VERSION
#error "CAPNP_VERSION is not defined, is capnp/generated-header-support.h missing?"
#elif CAPNP_VERSION != 1002000
#error "Version mismatch between generated code and library headers.  You must use the same version of the Cap'n Proto compiler and library."
#endif

#include "match.capnp.h"

CAPNP_BEGIN_HEADER

namespace capnp {
namespace schemas {

CAPNP_DECLARE_SCHEMA(c24b6cc6fc418df9);
CAPNP_DECLARE_SCHEMA(d9fbd819c7b90c04);
CAPNP_DECLARE_SCHEMA(93ed8eadf6d2f611);
CAPNP_DECLARE_SCHEMA(ca30dd1a61881e14);
CAPNP_DECLARE_SCHEMA(d7d7354203ff3ee7);
CAPNP_DECLARE_SCHEMA(a5c563f5e47f269b);
CAPNP_DECLARE_SCHEMA(f31a3b0e2119f63e);
CAPNP_DECLARE_SCHEMA(bfd642fe1003f5b0);
CAPNP_DECLARE_SCHEMA(8e8338034be7fdf9);
CAPNP_DECLARE_SCHEMA(e08c0dc1c2a0d0b0);
CAPNP_DECLARE_SCHEMA(b943b56283014590);
CAPNP_DECLARE_SCHEMA(8a9f2489106723d3);
CAPNP_DECLARE_SCHEMA(d451a3ec3e118996);
CAPNP_DECLARE_SCHEMA(fc81f34e1dd8cdcc);
CAPNP_DECLARE_SCHEMA(a558f407810cd239);
CAPNP_DECLARE_SCHEMA(9403cf0d1a49bfb8);
CAPNP_DECLARE_SCHEMA(fdfcc22bad8dd53d);
CAPNP_DECLARE_SCHEMA(8fb87e8e0ac5e59c);

}  // namespace schemas
}  // namespace capnp


struct GameSessionService {
  GameSessionService() = delete;

#if !CAPNP_LITE
  class Client;
  class Server;
#endif  // !CAPNP_LITE

  struct LoginParams;
  struct LoginResults;

  #if !CAPNP_LITE
  struct _capnpPrivate {
    CAPNP_DECLARE_INTERFACE_HEADER(c24b6cc6fc418df9)
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
  };
  #endif  // !CAPNP_LITE
};

struct GameSessionService::LoginParams {
  LoginParams() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(d9fbd819c7b90c04, 0, 1)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct GameSessionService::LoginResults {
  LoginResults() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(93ed8eadf6d2f611, 0, 1)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct UserSession {
  UserSession() = delete;

#if !CAPNP_LITE
  class Client;
  class Server;
#endif  // !CAPNP_LITE

  struct RequestMatchParams;
  struct RequestMatchResults;
  struct ReconnectParams;
  struct ReconnectResults;

  #if !CAPNP_LITE
  struct _capnpPrivate {
    CAPNP_DECLARE_INTERFACE_HEADER(ca30dd1a61881e14)
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
  };
  #endif  // !CAPNP_LITE
};

struct UserSession::RequestMatchParams {
  RequestMatchParams() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(d7d7354203ff3ee7, 0, 1)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct UserSession::RequestMatchResults {
  RequestMatchResults() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(a5c563f5e47f269b, 0, 2)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct UserSession::ReconnectParams {
  ReconnectParams() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(f31a3b0e2119f63e, 0, 1)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct UserSession::ReconnectResults {
  ReconnectResults() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(bfd642fe1003f5b0, 0, 1)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct MatchSession {
  MatchSession() = delete;

#if !CAPNP_LITE
  class Client;
  class Server;
#endif  // !CAPNP_LITE

  struct SubmitOutcomeParams;
  struct SubmitOutcomeResults;
  struct SubscribeToEventsParams;
  struct SubscribeToEventsResults;

  #if !CAPNP_LITE
  struct _capnpPrivate {
    CAPNP_DECLARE_INTERFACE_HEADER(8e8338034be7fdf9)
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
  };
  #endif  // !CAPNP_LITE
};

struct MatchSession::SubmitOutcomeParams {
  SubmitOutcomeParams() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(e08c0dc1c2a0d0b0, 0, 1)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct MatchSession::SubmitOutcomeResults {
  SubmitOutcomeResults() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(b943b56283014590, 0, 1)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct MatchSession::SubscribeToEventsParams {
  SubscribeToEventsParams() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(8a9f2489106723d3, 0, 1)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct MatchSession::SubscribeToEventsResults {
  SubscribeToEventsResults() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(d451a3ec3e118996, 0, 0)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct MatchListener {
  MatchListener() = delete;

#if !CAPNP_LITE
  class Client;
  class Server;
#endif  // !CAPNP_LITE

  struct OnMatchSettledParams;
  struct OnMatchSettledResults;
  struct OnOpponentDisconnectedParams;
  struct OnOpponentDisconnectedResults;

  #if !CAPNP_LITE
  struct _capnpPrivate {
    CAPNP_DECLARE_INTERFACE_HEADER(fc81f34e1dd8cdcc)
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
  };
  #endif  // !CAPNP_LITE
};

struct MatchListener::OnMatchSettledParams {
  OnMatchSettledParams() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(a558f407810cd239, 0, 1)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct MatchListener::OnMatchSettledResults {
  OnMatchSettledResults() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(9403cf0d1a49bfb8, 0, 0)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct MatchListener::OnOpponentDisconnectedParams {
  OnOpponentDisconnectedParams() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(fdfcc22bad8dd53d, 0, 0)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct MatchListener::OnOpponentDisconnectedResults {
  OnOpponentDisconnectedResults() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(8fb87e8e0ac5e59c, 0, 0)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

// =======================================================================================

#if !CAPNP_LITE
class GameSessionService::Client
    : public virtual ::capnp::Capability::Client {
public:
  typedef GameSessionService Calls;
  typedef GameSessionService Reads;

  Client(decltype(nullptr));
  explicit Client(::kj::Own< ::capnp::ClientHook>&& hook);
  template <typename _t, typename = ::kj::EnableIf< ::kj::canConvert<_t*, Server*>()>>
  Client(::kj::Own<_t>&& server);
  template <typename _t, typename = ::kj::EnableIf< ::kj::canConvert<_t*, Client*>()>>
  Client(::kj::Promise<_t>&& promise);
  Client(::kj::Exception&& exception);
  Client(Client&) = default;
  Client(Client&&) = default;
  Client& operator=(Client& other);
  Client& operator=(Client&& other);

  ::capnp::Request< ::GameSessionService::LoginParams,  ::GameSessionService::LoginResults> loginRequest(
      ::kj::Maybe< ::capnp::MessageSize> sizeHint = nullptr);

protected:
  Client() = default;
};

class GameSessionService::Server
    : public virtual ::capnp::Capability::Server {
public:
  typedef GameSessionService Serves;

  ::capnp::Capability::Server::DispatchCallResult dispatchCall(
      uint64_t interfaceId, uint16_t methodId,
      ::capnp::CallContext< ::capnp::AnyPointer, ::capnp::AnyPointer> context)
      override;

protected:
  typedef  ::GameSessionService::LoginParams LoginParams;
  typedef  ::GameSessionService::LoginResults LoginResults;
  typedef ::capnp::CallContext<LoginParams, LoginResults> LoginContext;
  virtual ::kj::Promise<void> login(LoginContext context);

  inline  ::GameSessionService::Client thisCap() {
    return ::capnp::Capability::Server::thisCap()
        .template castAs< ::GameSessionService>();
  }

  ::capnp::Capability::Server::DispatchCallResult dispatchCallInternal(
      uint16_t methodId,
      ::capnp::CallContext< ::capnp::AnyPointer, ::capnp::AnyPointer> context);
};
#endif  // !CAPNP_LITE

class GameSessionService::LoginParams::Reader {
public:
  typedef LoginParams Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline bool hasSignedChallenge() const;
  inline  ::capnp::Data::Reader getSignedChallenge() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class GameSessionService::LoginParams::Builder {
public:
  typedef LoginParams Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool hasSignedChallenge();
  inline  ::capnp::Data::Builder getSignedChallenge();
  inline void setSignedChallenge( ::capnp::Data::Reader value);
  inline  ::capnp::Data::Builder initSignedChallenge(unsigned int size);
  inline void adoptSignedChallenge(::capnp::Orphan< ::capnp::Data>&& value);
  inline ::capnp::Orphan< ::capnp::Data> disownSignedChallenge();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class GameSessionService::LoginParams::Pipeline {
public:
  typedef LoginParams Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class GameSessionService::LoginResults::Reader {
public:
  typedef LoginResults Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline bool hasSession() const;
#if !CAPNP_LITE
  inline  ::UserSession::Client getSession() const;
#endif  // !CAPNP_LITE

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class GameSessionService::LoginResults::Builder {
public:
  typedef LoginResults Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool hasSession();
#if !CAPNP_LITE
  inline  ::UserSession::Client getSession();
  inline void setSession( ::UserSession::Client&& value);
  inline void setSession( ::UserSession::Client& value);
  inline void adoptSession(::capnp::Orphan< ::UserSession>&& value);
  inline ::capnp::Orphan< ::UserSession> disownSession();
#endif  // !CAPNP_LITE

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class GameSessionService::LoginResults::Pipeline {
public:
  typedef LoginResults Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

  inline  ::UserSession::Client getSession();
private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

#if !CAPNP_LITE
class UserSession::Client
    : public virtual ::capnp::Capability::Client {
public:
  typedef UserSession Calls;
  typedef UserSession Reads;

  Client(decltype(nullptr));
  explicit Client(::kj::Own< ::capnp::ClientHook>&& hook);
  template <typename _t, typename = ::kj::EnableIf< ::kj::canConvert<_t*, Server*>()>>
  Client(::kj::Own<_t>&& server);
  template <typename _t, typename = ::kj::EnableIf< ::kj::canConvert<_t*, Client*>()>>
  Client(::kj::Promise<_t>&& promise);
  Client(::kj::Exception&& exception);
  Client(Client&) = default;
  Client(Client&&) = default;
  Client& operator=(Client& other);
  Client& operator=(Client&& other);

  ::capnp::Request< ::UserSession::RequestMatchParams,  ::UserSession::RequestMatchResults> requestMatchRequest(
      ::kj::Maybe< ::capnp::MessageSize> sizeHint = nullptr);
  ::capnp::Request< ::UserSession::ReconnectParams,  ::UserSession::ReconnectResults> reconnectRequest(
      ::kj::Maybe< ::capnp::MessageSize> sizeHint = nullptr);

protected:
  Client() = default;
};

class UserSession::Server
    : public virtual ::capnp::Capability::Server {
public:
  typedef UserSession Serves;

  ::capnp::Capability::Server::DispatchCallResult dispatchCall(
      uint64_t interfaceId, uint16_t methodId,
      ::capnp::CallContext< ::capnp::AnyPointer, ::capnp::AnyPointer> context)
      override;

protected:
  typedef  ::UserSession::RequestMatchParams RequestMatchParams;
  typedef  ::UserSession::RequestMatchResults RequestMatchResults;
  typedef ::capnp::CallContext<RequestMatchParams, RequestMatchResults> RequestMatchContext;
  virtual ::kj::Promise<void> requestMatch(RequestMatchContext context);
  typedef  ::UserSession::ReconnectParams ReconnectParams;
  typedef  ::UserSession::ReconnectResults ReconnectResults;
  typedef ::capnp::CallContext<ReconnectParams, ReconnectResults> ReconnectContext;
  virtual ::kj::Promise<void> reconnect(ReconnectContext context);

  inline  ::UserSession::Client thisCap() {
    return ::capnp::Capability::Server::thisCap()
        .template castAs< ::UserSession>();
  }

  ::capnp::Capability::Server::DispatchCallResult dispatchCallInternal(
      uint16_t methodId,
      ::capnp::CallContext< ::capnp::AnyPointer, ::capnp::AnyPointer> context);
};
#endif  // !CAPNP_LITE

class UserSession::RequestMatchParams::Reader {
public:
  typedef RequestMatchParams Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline bool hasReq() const;
  inline  ::GameMatchRequest::Reader getReq() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class UserSession::RequestMatchParams::Builder {
public:
  typedef RequestMatchParams Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool hasReq();
  inline  ::GameMatchRequest::Builder getReq();
  inline void setReq( ::GameMatchRequest::Reader value);
  inline  ::GameMatchRequest::Builder initReq();
  inline void adoptReq(::capnp::Orphan< ::GameMatchRequest>&& value);
  inline ::capnp::Orphan< ::GameMatchRequest> disownReq();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class UserSession::RequestMatchParams::Pipeline {
public:
  typedef RequestMatchParams Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

  inline  ::GameMatchRequest::Pipeline getReq();
private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class UserSession::RequestMatchResults::Reader {
public:
  typedef RequestMatchResults Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline bool hasAssignment() const;
  inline  ::MatchAssignment::Reader getAssignment() const;

  inline bool hasSession() const;
#if !CAPNP_LITE
  inline  ::MatchSession::Client getSession() const;
#endif  // !CAPNP_LITE

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class UserSession::RequestMatchResults::Builder {
public:
  typedef RequestMatchResults Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool hasAssignment();
  inline  ::MatchAssignment::Builder getAssignment();
  inline void setAssignment( ::MatchAssignment::Reader value);
  inline  ::MatchAssignment::Builder initAssignment();
  inline void adoptAssignment(::capnp::Orphan< ::MatchAssignment>&& value);
  inline ::capnp::Orphan< ::MatchAssignment> disownAssignment();

  inline bool hasSession();
#if !CAPNP_LITE
  inline  ::MatchSession::Client getSession();
  inline void setSession( ::MatchSession::Client&& value);
  inline void setSession( ::MatchSession::Client& value);
  inline void adoptSession(::capnp::Orphan< ::MatchSession>&& value);
  inline ::capnp::Orphan< ::MatchSession> disownSession();
#endif  // !CAPNP_LITE

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class UserSession::RequestMatchResults::Pipeline {
public:
  typedef RequestMatchResults Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

  inline  ::MatchAssignment::Pipeline getAssignment();
  inline  ::MatchSession::Client getSession();
private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class UserSession::ReconnectParams::Reader {
public:
  typedef ReconnectParams Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline bool hasMatchId() const;
  inline  ::capnp::Data::Reader getMatchId() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class UserSession::ReconnectParams::Builder {
public:
  typedef ReconnectParams Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool hasMatchId();
  inline  ::capnp::Data::Builder getMatchId();
  inline void setMatchId( ::capnp::Data::Reader value);
  inline  ::capnp::Data::Builder initMatchId(unsigned int size);
  inline void adoptMatchId(::capnp::Orphan< ::capnp::Data>&& value);
  inline ::capnp::Orphan< ::capnp::Data> disownMatchId();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class UserSession::ReconnectParams::Pipeline {
public:
  typedef ReconnectParams Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class UserSession::ReconnectResults::Reader {
public:
  typedef ReconnectResults Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline bool hasSession() const;
#if !CAPNP_LITE
  inline  ::MatchSession::Client getSession() const;
#endif  // !CAPNP_LITE

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class UserSession::ReconnectResults::Builder {
public:
  typedef ReconnectResults Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool hasSession();
#if !CAPNP_LITE
  inline  ::MatchSession::Client getSession();
  inline void setSession( ::MatchSession::Client&& value);
  inline void setSession( ::MatchSession::Client& value);
  inline void adoptSession(::capnp::Orphan< ::MatchSession>&& value);
  inline ::capnp::Orphan< ::MatchSession> disownSession();
#endif  // !CAPNP_LITE

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class UserSession::ReconnectResults::Pipeline {
public:
  typedef ReconnectResults Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

  inline  ::MatchSession::Client getSession();
private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

#if !CAPNP_LITE
class MatchSession::Client
    : public virtual ::capnp::Capability::Client {
public:
  typedef MatchSession Calls;
  typedef MatchSession Reads;

  Client(decltype(nullptr));
  explicit Client(::kj::Own< ::capnp::ClientHook>&& hook);
  template <typename _t, typename = ::kj::EnableIf< ::kj::canConvert<_t*, Server*>()>>
  Client(::kj::Own<_t>&& server);
  template <typename _t, typename = ::kj::EnableIf< ::kj::canConvert<_t*, Client*>()>>
  Client(::kj::Promise<_t>&& promise);
  Client(::kj::Exception&& exception);
  Client(Client&) = default;
  Client(Client&&) = default;
  Client& operator=(Client& other);
  Client& operator=(Client&& other);

  ::capnp::Request< ::MatchSession::SubmitOutcomeParams,  ::MatchSession::SubmitOutcomeResults> submitOutcomeRequest(
      ::kj::Maybe< ::capnp::MessageSize> sizeHint = nullptr);
  ::capnp::Request< ::MatchSession::SubscribeToEventsParams,  ::MatchSession::SubscribeToEventsResults> subscribeToEventsRequest(
      ::kj::Maybe< ::capnp::MessageSize> sizeHint = nullptr);

protected:
  Client() = default;
};

class MatchSession::Server
    : public virtual ::capnp::Capability::Server {
public:
  typedef MatchSession Serves;

  ::capnp::Capability::Server::DispatchCallResult dispatchCall(
      uint64_t interfaceId, uint16_t methodId,
      ::capnp::CallContext< ::capnp::AnyPointer, ::capnp::AnyPointer> context)
      override;

protected:
  typedef  ::MatchSession::SubmitOutcomeParams SubmitOutcomeParams;
  typedef  ::MatchSession::SubmitOutcomeResults SubmitOutcomeResults;
  typedef ::capnp::CallContext<SubmitOutcomeParams, SubmitOutcomeResults> SubmitOutcomeContext;
  virtual ::kj::Promise<void> submitOutcome(SubmitOutcomeContext context);
  typedef  ::MatchSession::SubscribeToEventsParams SubscribeToEventsParams;
  typedef  ::MatchSession::SubscribeToEventsResults SubscribeToEventsResults;
  typedef ::capnp::CallContext<SubscribeToEventsParams, SubscribeToEventsResults> SubscribeToEventsContext;
  virtual ::kj::Promise<void> subscribeToEvents(SubscribeToEventsContext context);

  inline  ::MatchSession::Client thisCap() {
    return ::capnp::Capability::Server::thisCap()
        .template castAs< ::MatchSession>();
  }

  ::capnp::Capability::Server::DispatchCallResult dispatchCallInternal(
      uint16_t methodId,
      ::capnp::CallContext< ::capnp::AnyPointer, ::capnp::AnyPointer> context);
};
#endif  // !CAPNP_LITE

class MatchSession::SubmitOutcomeParams::Reader {
public:
  typedef SubmitOutcomeParams Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline bool hasSubmission() const;
  inline  ::OutcomeSubmission::Reader getSubmission() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class MatchSession::SubmitOutcomeParams::Builder {
public:
  typedef SubmitOutcomeParams Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool hasSubmission();
  inline  ::OutcomeSubmission::Builder getSubmission();
  inline void setSubmission( ::OutcomeSubmission::Reader value);
  inline  ::OutcomeSubmission::Builder initSubmission();
  inline void adoptSubmission(::capnp::Orphan< ::OutcomeSubmission>&& value);
  inline ::capnp::Orphan< ::OutcomeSubmission> disownSubmission();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class MatchSession::SubmitOutcomeParams::Pipeline {
public:
  typedef SubmitOutcomeParams Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

  inline  ::OutcomeSubmission::Pipeline getSubmission();
private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class MatchSession::SubmitOutcomeResults::Reader {
public:
  typedef SubmitOutcomeResults Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline bool hasSignature() const;
  inline  ::capnp::Data::Reader getSignature() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class MatchSession::SubmitOutcomeResults::Builder {
public:
  typedef SubmitOutcomeResults Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool hasSignature();
  inline  ::capnp::Data::Builder getSignature();
  inline void setSignature( ::capnp::Data::Reader value);
  inline  ::capnp::Data::Builder initSignature(unsigned int size);
  inline void adoptSignature(::capnp::Orphan< ::capnp::Data>&& value);
  inline ::capnp::Orphan< ::capnp::Data> disownSignature();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class MatchSession::SubmitOutcomeResults::Pipeline {
public:
  typedef SubmitOutcomeResults Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class MatchSession::SubscribeToEventsParams::Reader {
public:
  typedef SubscribeToEventsParams Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline bool hasSubscriber() const;
#if !CAPNP_LITE
  inline  ::MatchListener::Client getSubscriber() const;
#endif  // !CAPNP_LITE

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class MatchSession::SubscribeToEventsParams::Builder {
public:
  typedef SubscribeToEventsParams Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool hasSubscriber();
#if !CAPNP_LITE
  inline  ::MatchListener::Client getSubscriber();
  inline void setSubscriber( ::MatchListener::Client&& value);
  inline void setSubscriber( ::MatchListener::Client& value);
  inline void adoptSubscriber(::capnp::Orphan< ::MatchListener>&& value);
  inline ::capnp::Orphan< ::MatchListener> disownSubscriber();
#endif  // !CAPNP_LITE

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class MatchSession::SubscribeToEventsParams::Pipeline {
public:
  typedef SubscribeToEventsParams Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

  inline  ::MatchListener::Client getSubscriber();
private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class MatchSession::SubscribeToEventsResults::Reader {
public:
  typedef SubscribeToEventsResults Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class MatchSession::SubscribeToEventsResults::Builder {
public:
  typedef SubscribeToEventsResults Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class MatchSession::SubscribeToEventsResults::Pipeline {
public:
  typedef SubscribeToEventsResults Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

#if !CAPNP_LITE
class MatchListener::Client
    : public virtual ::capnp::Capability::Client {
public:
  typedef MatchListener Calls;
  typedef MatchListener Reads;

  Client(decltype(nullptr));
  explicit Client(::kj::Own< ::capnp::ClientHook>&& hook);
  template <typename _t, typename = ::kj::EnableIf< ::kj::canConvert<_t*, Server*>()>>
  Client(::kj::Own<_t>&& server);
  template <typename _t, typename = ::kj::EnableIf< ::kj::canConvert<_t*, Client*>()>>
  Client(::kj::Promise<_t>&& promise);
  Client(::kj::Exception&& exception);
  Client(Client&) = default;
  Client(Client&&) = default;
  Client& operator=(Client& other);
  Client& operator=(Client&& other);

  ::capnp::Request< ::MatchListener::OnMatchSettledParams,  ::MatchListener::OnMatchSettledResults> onMatchSettledRequest(
      ::kj::Maybe< ::capnp::MessageSize> sizeHint = nullptr);
  ::capnp::Request< ::MatchListener::OnOpponentDisconnectedParams,  ::MatchListener::OnOpponentDisconnectedResults> onOpponentDisconnectedRequest(
      ::kj::Maybe< ::capnp::MessageSize> sizeHint = nullptr);

protected:
  Client() = default;
};

class MatchListener::Server
    : public virtual ::capnp::Capability::Server {
public:
  typedef MatchListener Serves;

  ::capnp::Capability::Server::DispatchCallResult dispatchCall(
      uint64_t interfaceId, uint16_t methodId,
      ::capnp::CallContext< ::capnp::AnyPointer, ::capnp::AnyPointer> context)
      override;

protected:
  typedef  ::MatchListener::OnMatchSettledParams OnMatchSettledParams;
  typedef  ::MatchListener::OnMatchSettledResults OnMatchSettledResults;
  typedef ::capnp::CallContext<OnMatchSettledParams, OnMatchSettledResults> OnMatchSettledContext;
  virtual ::kj::Promise<void> onMatchSettled(OnMatchSettledContext context);
  typedef  ::MatchListener::OnOpponentDisconnectedParams OnOpponentDisconnectedParams;
  typedef  ::MatchListener::OnOpponentDisconnectedResults OnOpponentDisconnectedResults;
  typedef ::capnp::CallContext<OnOpponentDisconnectedParams, OnOpponentDisconnectedResults> OnOpponentDisconnectedContext;
  virtual ::kj::Promise<void> onOpponentDisconnected(OnOpponentDisconnectedContext context);

  inline  ::MatchListener::Client thisCap() {
    return ::capnp::Capability::Server::thisCap()
        .template castAs< ::MatchListener>();
  }

  ::capnp::Capability::Server::DispatchCallResult dispatchCallInternal(
      uint16_t methodId,
      ::capnp::CallContext< ::capnp::AnyPointer, ::capnp::AnyPointer> context);
};
#endif  // !CAPNP_LITE

class MatchListener::OnMatchSettledParams::Reader {
public:
  typedef OnMatchSettledParams Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline bool hasOutcome() const;
  inline  ::Outcome::Reader getOutcome() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class MatchListener::OnMatchSettledParams::Builder {
public:
  typedef OnMatchSettledParams Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool hasOutcome();
  inline  ::Outcome::Builder getOutcome();
  inline void setOutcome( ::Outcome::Reader value);
  inline  ::Outcome::Builder initOutcome();
  inline void adoptOutcome(::capnp::Orphan< ::Outcome>&& value);
  inline ::capnp::Orphan< ::Outcome> disownOutcome();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class MatchListener::OnMatchSettledParams::Pipeline {
public:
  typedef OnMatchSettledParams Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

  inline  ::Outcome::Pipeline getOutcome();
private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class MatchListener::OnMatchSettledResults::Reader {
public:
  typedef OnMatchSettledResults Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class MatchListener::OnMatchSettledResults::Builder {
public:
  typedef OnMatchSettledResults Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class MatchListener::OnMatchSettledResults::Pipeline {
public:
  typedef OnMatchSettledResults Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class MatchListener::OnOpponentDisconnectedParams::Reader {
public:
  typedef OnOpponentDisconnectedParams Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class MatchListener::OnOpponentDisconnectedParams::Builder {
public:
  typedef OnOpponentDisconnectedParams Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class MatchListener::OnOpponentDisconnectedParams::Pipeline {
public:
  typedef OnOpponentDisconnectedParams Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class MatchListener::OnOpponentDisconnectedResults::Reader {
public:
  typedef OnOpponentDisconnectedResults Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class MatchListener::OnOpponentDisconnectedResults::Builder {
public:
  typedef OnOpponentDisconnectedResults Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class MatchListener::OnOpponentDisconnectedResults::Pipeline {
public:
  typedef OnOpponentDisconnectedResults Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

// =======================================================================================

#if !CAPNP_LITE
inline GameSessionService::Client::Client(decltype(nullptr))
    : ::capnp::Capability::Client(nullptr) {}
inline GameSessionService::Client::Client(
    ::kj::Own< ::capnp::ClientHook>&& hook)
    : ::capnp::Capability::Client(::kj::mv(hook)) {}
template <typename _t, typename>
inline GameSessionService::Client::Client(::kj::Own<_t>&& server)
    : ::capnp::Capability::Client(::kj::mv(server)) {}
template <typename _t, typename>
inline GameSessionService::Client::Client(::kj::Promise<_t>&& promise)
    : ::capnp::Capability::Client(::kj::mv(promise)) {}
inline GameSessionService::Client::Client(::kj::Exception&& exception)
    : ::capnp::Capability::Client(::kj::mv(exception)) {}
inline  ::GameSessionService::Client& GameSessionService::Client::operator=(Client& other) {
  ::capnp::Capability::Client::operator=(other);
  return *this;
}
inline  ::GameSessionService::Client& GameSessionService::Client::operator=(Client&& other) {
  ::capnp::Capability::Client::operator=(kj::mv(other));
  return *this;
}

#endif  // !CAPNP_LITE
inline bool GameSessionService::LoginParams::Reader::hasSignedChallenge() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool GameSessionService::LoginParams::Builder::hasSignedChallenge() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Data::Reader GameSessionService::LoginParams::Reader::getSignedChallenge() const {
  return ::capnp::_::PointerHelpers< ::capnp::Data>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::capnp::Data::Builder GameSessionService::LoginParams::Builder::getSignedChallenge() {
  return ::capnp::_::PointerHelpers< ::capnp::Data>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void GameSessionService::LoginParams::Builder::setSignedChallenge( ::capnp::Data::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Data>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Data::Builder GameSessionService::LoginParams::Builder::initSignedChallenge(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Data>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), size);
}
inline void GameSessionService::LoginParams::Builder::adoptSignedChallenge(
    ::capnp::Orphan< ::capnp::Data>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Data>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Data> GameSessionService::LoginParams::Builder::disownSignedChallenge() {
  return ::capnp::_::PointerHelpers< ::capnp::Data>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool GameSessionService::LoginResults::Reader::hasSession() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool GameSessionService::LoginResults::Builder::hasSession() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
#if !CAPNP_LITE
inline  ::UserSession::Client GameSessionService::LoginResults::Reader::getSession() const {
  return ::capnp::_::PointerHelpers< ::UserSession>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::UserSession::Client GameSessionService::LoginResults::Builder::getSession() {
  return ::capnp::_::PointerHelpers< ::UserSession>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::UserSession::Client GameSessionService::LoginResults::Pipeline::getSession() {
  return  ::UserSession::Client(_typeless.getPointerField(0).asCap());
}
inline void GameSessionService::LoginResults::Builder::setSession( ::UserSession::Client&& cap) {
  ::capnp::_::PointerHelpers< ::UserSession>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(cap));
}
inline void GameSessionService::LoginResults::Builder::setSession( ::UserSession::Client& cap) {
  ::capnp::_::PointerHelpers< ::UserSession>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), cap);
}
inline void GameSessionService::LoginResults::Builder::adoptSession(
    ::capnp::Orphan< ::UserSession>&& value) {
  ::capnp::_::PointerHelpers< ::UserSession>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::UserSession> GameSessionService::LoginResults::Builder::disownSession() {
  return ::capnp::_::PointerHelpers< ::UserSession>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
#endif  // !CAPNP_LITE

#if !CAPNP_LITE
inline UserSession::Client::Client(decltype(nullptr))
    : ::capnp::Capability::Client(nullptr) {}
inline UserSession::Client::Client(
    ::kj::Own< ::capnp::ClientHook>&& hook)
    : ::capnp::Capability::Client(::kj::mv(hook)) {}
template <typename _t, typename>
inline UserSession::Client::Client(::kj::Own<_t>&& server)
    : ::capnp::Capability::Client(::kj::mv(server)) {}
template <typename _t, typename>
inline UserSession::Client::Client(::kj::Promise<_t>&& promise)
    : ::capnp::Capability::Client(::kj::mv(promise)) {}
inline UserSession::Client::Client(::kj::Exception&& exception)
    : ::capnp::Capability::Client(::kj::mv(exception)) {}
inline  ::UserSession::Client& UserSession::Client::operator=(Client& other) {
  ::capnp::Capability::Client::operator=(other);
  return *this;
}
inline  ::UserSession::Client& UserSession::Client::operator=(Client&& other) {
  ::capnp::Capability::Client::operator=(kj::mv(other));
  return *this;
}

#endif  // !CAPNP_LITE
inline bool UserSession::RequestMatchParams::Reader::hasReq() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool UserSession::RequestMatchParams::Builder::hasReq() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::GameMatchRequest::Reader UserSession::RequestMatchParams::Reader::getReq() const {
  return ::capnp::_::PointerHelpers< ::GameMatchRequest>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::GameMatchRequest::Builder UserSession::RequestMatchParams::Builder::getReq() {
  return ::capnp::_::PointerHelpers< ::GameMatchRequest>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
#if !CAPNP_LITE
inline  ::GameMatchRequest::Pipeline UserSession::RequestMatchParams::Pipeline::getReq() {
  return  ::GameMatchRequest::Pipeline(_typeless.getPointerField(0));
}
#endif  // !CAPNP_LITE
inline void UserSession::RequestMatchParams::Builder::setReq( ::GameMatchRequest::Reader value) {
  ::capnp::_::PointerHelpers< ::GameMatchRequest>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::GameMatchRequest::Builder UserSession::RequestMatchParams::Builder::initReq() {
  return ::capnp::_::PointerHelpers< ::GameMatchRequest>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void UserSession::RequestMatchParams::Builder::adoptReq(
    ::capnp::Orphan< ::GameMatchRequest>&& value) {
  ::capnp::_::PointerHelpers< ::GameMatchRequest>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::GameMatchRequest> UserSession::RequestMatchParams::Builder::disownReq() {
  return ::capnp::_::PointerHelpers< ::GameMatchRequest>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool UserSession::RequestMatchResults::Reader::hasAssignment() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool UserSession::RequestMatchResults::Builder::hasAssignment() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::MatchAssignment::Reader UserSession::RequestMatchResults::Reader::getAssignment() const {
  return ::capnp::_::PointerHelpers< ::MatchAssignment>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::MatchAssignment::Builder UserSession::RequestMatchResults::Builder::getAssignment() {
  return ::capnp::_::PointerHelpers< ::MatchAssignment>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
#if !CAPNP_LITE
inline  ::MatchAssignment::Pipeline UserSession::RequestMatchResults::Pipeline::getAssignment() {
  return  ::MatchAssignment::Pipeline(_typeless.getPointerField(0));
}
#endif  // !CAPNP_LITE
inline void UserSession::RequestMatchResults::Builder::setAssignment( ::MatchAssignment::Reader value) {
  ::capnp::_::PointerHelpers< ::MatchAssignment>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::MatchAssignment::Builder UserSession::RequestMatchResults::Builder::initAssignment() {
  return ::capnp::_::PointerHelpers< ::MatchAssignment>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void UserSession::RequestMatchResults::Builder::adoptAssignment(
    ::capnp::Orphan< ::MatchAssignment>&& value) {
  ::capnp::_::PointerHelpers< ::MatchAssignment>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::MatchAssignment> UserSession::RequestMatchResults::Builder::disownAssignment() {
  return ::capnp::_::PointerHelpers< ::MatchAssignment>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool UserSession::RequestMatchResults::Reader::hasSession() const {
  return !_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline bool UserSession::RequestMatchResults::Builder::hasSession() {
  return !_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
#if !CAPNP_LITE
inline  ::MatchSession::Client UserSession::RequestMatchResults::Reader::getSession() const {
  return ::capnp::_::PointerHelpers< ::MatchSession>::get(_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline  ::MatchSession::Client UserSession::RequestMatchResults::Builder::getSession() {
  return ::capnp::_::PointerHelpers< ::MatchSession>::get(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline  ::MatchSession::Client UserSession::RequestMatchResults::Pipeline::getSession() {
  return  ::MatchSession::Client(_typeless.getPointerField(1).asCap());
}
inline void UserSession::RequestMatchResults::Builder::setSession( ::MatchSession::Client&& cap) {
  ::capnp::_::PointerHelpers< ::MatchSession>::set(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), kj::mv(cap));
}
inline void UserSession::RequestMatchResults::Builder::setSession( ::MatchSession::Client& cap) {
  ::capnp::_::PointerHelpers< ::MatchSession>::set(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), cap);
}
inline void UserSession::RequestMatchResults::Builder::adoptSession(
    ::capnp::Orphan< ::MatchSession>&& value) {
  ::capnp::_::PointerHelpers< ::MatchSession>::adopt(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::MatchSession> UserSession::RequestMatchResults::Builder::disownSession() {
  return ::capnp::_::PointerHelpers< ::MatchSession>::disown(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
#endif  // !CAPNP_LITE

inline bool UserSession::ReconnectParams::Reader::hasMatchId() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool UserSession::ReconnectParams::Builder::hasMatchId() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Data::Reader UserSession::ReconnectParams::Reader::getMatchId() const {
  return ::capnp::_::PointerHelpers< ::capnp::Data>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::capnp::Data::Builder UserSession::ReconnectParams::Builder::getMatchId() {
  return ::capnp::_::PointerHelpers< ::capnp::Data>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void UserSession::ReconnectParams::Builder::setMatchId( ::capnp::Data::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Data>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Data::Builder UserSession::ReconnectParams::Builder::initMatchId(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Data>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), size);
}
inline void UserSession::ReconnectParams::Builder::adoptMatchId(
    ::capnp::Orphan< ::capnp::Data>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Data>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Data> UserSession::ReconnectParams::Builder::disownMatchId() {
  return ::capnp::_::PointerHelpers< ::capnp::Data>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool UserSession::ReconnectResults::Reader::hasSession() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool UserSession::ReconnectResults::Builder::hasSession() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
#if !CAPNP_LITE
inline  ::MatchSession::Client UserSession::ReconnectResults::Reader::getSession() const {
  return ::capnp::_::PointerHelpers< ::MatchSession>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::MatchSession::Client UserSession::ReconnectResults::Builder::getSession() {
  return ::capnp::_::PointerHelpers< ::MatchSession>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::MatchSession::Client UserSession::ReconnectResults::Pipeline::getSession() {
  return  ::MatchSession::Client(_typeless.getPointerField(0).asCap());
}
inline void UserSession::ReconnectResults::Builder::setSession( ::MatchSession::Client&& cap) {
  ::capnp::_::PointerHelpers< ::MatchSession>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(cap));
}
inline void UserSession::ReconnectResults::Builder::setSession( ::MatchSession::Client& cap) {
  ::capnp::_::PointerHelpers< ::MatchSession>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), cap);
}
inline void UserSession::ReconnectResults::Builder::adoptSession(
    ::capnp::Orphan< ::MatchSession>&& value) {
  ::capnp::_::PointerHelpers< ::MatchSession>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::MatchSession> UserSession::ReconnectResults::Builder::disownSession() {
  return ::capnp::_::PointerHelpers< ::MatchSession>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
#endif  // !CAPNP_LITE

#if !CAPNP_LITE
inline MatchSession::Client::Client(decltype(nullptr))
    : ::capnp::Capability::Client(nullptr) {}
inline MatchSession::Client::Client(
    ::kj::Own< ::capnp::ClientHook>&& hook)
    : ::capnp::Capability::Client(::kj::mv(hook)) {}
template <typename _t, typename>
inline MatchSession::Client::Client(::kj::Own<_t>&& server)
    : ::capnp::Capability::Client(::kj::mv(server)) {}
template <typename _t, typename>
inline MatchSession::Client::Client(::kj::Promise<_t>&& promise)
    : ::capnp::Capability::Client(::kj::mv(promise)) {}
inline MatchSession::Client::Client(::kj::Exception&& exception)
    : ::capnp::Capability::Client(::kj::mv(exception)) {}
inline  ::MatchSession::Client& MatchSession::Client::operator=(Client& other) {
  ::capnp::Capability::Client::operator=(other);
  return *this;
}
inline  ::MatchSession::Client& MatchSession::Client::operator=(Client&& other) {
  ::capnp::Capability::Client::operator=(kj::mv(other));
  return *this;
}

#endif  // !CAPNP_LITE
inline bool MatchSession::SubmitOutcomeParams::Reader::hasSubmission() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool MatchSession::SubmitOutcomeParams::Builder::hasSubmission() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::OutcomeSubmission::Reader MatchSession::SubmitOutcomeParams::Reader::getSubmission() const {
  return ::capnp::_::PointerHelpers< ::OutcomeSubmission>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::OutcomeSubmission::Builder MatchSession::SubmitOutcomeParams::Builder::getSubmission() {
  return ::capnp::_::PointerHelpers< ::OutcomeSubmission>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
#if !CAPNP_LITE
inline  ::OutcomeSubmission::Pipeline MatchSession::SubmitOutcomeParams::Pipeline::getSubmission() {
  return  ::OutcomeSubmission::Pipeline(_typeless.getPointerField(0));
}
#endif  // !CAPNP_LITE
inline void MatchSession::SubmitOutcomeParams::Builder::setSubmission( ::OutcomeSubmission::Reader value) {
  ::capnp::_::PointerHelpers< ::OutcomeSubmission>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::OutcomeSubmission::Builder MatchSession::SubmitOutcomeParams::Builder::initSubmission() {
  return ::capnp::_::PointerHelpers< ::OutcomeSubmission>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void MatchSession::SubmitOutcomeParams::Builder::adoptSubmission(
    ::capnp::Orphan< ::OutcomeSubmission>&& value) {
  ::capnp::_::PointerHelpers< ::OutcomeSubmission>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::OutcomeSubmission> MatchSession::SubmitOutcomeParams::Builder::disownSubmission() {
  return ::capnp::_::PointerHelpers< ::OutcomeSubmission>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool MatchSession::SubmitOutcomeResults::Reader::hasSignature() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool MatchSession::SubmitOutcomeResults::Builder::hasSignature() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Data::Reader MatchSession::SubmitOutcomeResults::Reader::getSignature() const {
  return ::capnp::_::PointerHelpers< ::capnp::Data>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::capnp::Data::Builder MatchSession::SubmitOutcomeResults::Builder::getSignature() {
  return ::capnp::_::PointerHelpers< ::capnp::Data>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void MatchSession::SubmitOutcomeResults::Builder::setSignature( ::capnp::Data::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Data>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Data::Builder MatchSession::SubmitOutcomeResults::Builder::initSignature(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Data>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), size);
}
inline void MatchSession::SubmitOutcomeResults::Builder::adoptSignature(
    ::capnp::Orphan< ::capnp::Data>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Data>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Data> MatchSession::SubmitOutcomeResults::Builder::disownSignature() {
  return ::capnp::_::PointerHelpers< ::capnp::Data>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool MatchSession::SubscribeToEventsParams::Reader::hasSubscriber() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool MatchSession::SubscribeToEventsParams::Builder::hasSubscriber() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
#if !CAPNP_LITE
inline  ::MatchListener::Client MatchSession::SubscribeToEventsParams::Reader::getSubscriber() const {
  return ::capnp::_::PointerHelpers< ::MatchListener>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::MatchListener::Client MatchSession::SubscribeToEventsParams::Builder::getSubscriber() {
  return ::capnp::_::PointerHelpers< ::MatchListener>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::MatchListener::Client MatchSession::SubscribeToEventsParams::Pipeline::getSubscriber() {
  return  ::MatchListener::Client(_typeless.getPointerField(0).asCap());
}
inline void MatchSession::SubscribeToEventsParams::Builder::setSubscriber( ::MatchListener::Client&& cap) {
  ::capnp::_::PointerHelpers< ::MatchListener>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(cap));
}
inline void MatchSession::SubscribeToEventsParams::Builder::setSubscriber( ::MatchListener::Client& cap) {
  ::capnp::_::PointerHelpers< ::MatchListener>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), cap);
}
inline void MatchSession::SubscribeToEventsParams::Builder::adoptSubscriber(
    ::capnp::Orphan< ::MatchListener>&& value) {
  ::capnp::_::PointerHelpers< ::MatchListener>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::MatchListener> MatchSession::SubscribeToEventsParams::Builder::disownSubscriber() {
  return ::capnp::_::PointerHelpers< ::MatchListener>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
#endif  // !CAPNP_LITE

#if !CAPNP_LITE
inline MatchListener::Client::Client(decltype(nullptr))
    : ::capnp::Capability::Client(nullptr) {}
inline MatchListener::Client::Client(
    ::kj::Own< ::capnp::ClientHook>&& hook)
    : ::capnp::Capability::Client(::kj::mv(hook)) {}
template <typename _t, typename>
inline MatchListener::Client::Client(::kj::Own<_t>&& server)
    : ::capnp::Capability::Client(::kj::mv(server)) {}
template <typename _t, typename>
inline MatchListener::Client::Client(::kj::Promise<_t>&& promise)
    : ::capnp::Capability::Client(::kj::mv(promise)) {}
inline MatchListener::Client::Client(::kj::Exception&& exception)
    : ::capnp::Capability::Client(::kj::mv(exception)) {}
inline  ::MatchListener::Client& MatchListener::Client::operator=(Client& other) {
  ::capnp::Capability::Client::operator=(other);
  return *this;
}
inline  ::MatchListener::Client& MatchListener::Client::operator=(Client&& other) {
  ::capnp::Capability::Client::operator=(kj::mv(other));
  return *this;
}

#endif  // !CAPNP_LITE
inline bool MatchListener::OnMatchSettledParams::Reader::hasOutcome() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool MatchListener::OnMatchSettledParams::Builder::hasOutcome() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::Outcome::Reader MatchListener::OnMatchSettledParams::Reader::getOutcome() const {
  return ::capnp::_::PointerHelpers< ::Outcome>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::Outcome::Builder MatchListener::OnMatchSettledParams::Builder::getOutcome() {
  return ::capnp::_::PointerHelpers< ::Outcome>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
#if !CAPNP_LITE
inline  ::Outcome::Pipeline MatchListener::OnMatchSettledParams::Pipeline::getOutcome() {
  return  ::Outcome::Pipeline(_typeless.getPointerField(0));
}
#endif  // !CAPNP_LITE
inline void MatchListener::OnMatchSettledParams::Builder::setOutcome( ::Outcome::Reader value) {
  ::capnp::_::PointerHelpers< ::Outcome>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::Outcome::Builder MatchListener::OnMatchSettledParams::Builder::initOutcome() {
  return ::capnp::_::PointerHelpers< ::Outcome>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void MatchListener::OnMatchSettledParams::Builder::adoptOutcome(
    ::capnp::Orphan< ::Outcome>&& value) {
  ::capnp::_::PointerHelpers< ::Outcome>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::Outcome> MatchListener::OnMatchSettledParams::Builder::disownOutcome() {
  return ::capnp::_::PointerHelpers< ::Outcome>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}


CAPNP_END_HEADER

